module.exports = {
  plugins: ["node"],

  rules: {
    "node/callback-return": "error",
    "node/exports-style": "error",
    "node/file-extension-in-import": "error",
    "node/global-require": "error",
    "node/handle-callback-err": "error",
    "node/no-callback-literal": "error",
    "node/no-deprecated-api": "error",
    "node/no-exports-assign": "error",
    "node/no-extraneous-import": "error",
    "node/no-extraneous-require": "error",
    "node/no-hide-core-modules": "error",
    "node/no-missing-import": "error",
    "node/no-missing-require": "error",
    "node/no-mixed-requires": "error",
    "node/no-new-require": "error",
    "node/no-path-concat": "error",
    "node/no-process-env": "off",
    "node/no-process-exit": "error",
    "node/no-restricted-import": "error",
    "node/no-restricted-require": "error",
    "node/no-sync": "error",
    "node/no-unpublished-bin": "error",
    "node/no-unpublished-import": "error",
    "node/no-unpublished-require": "off",
    "node/no-unsupported-features": "error",
    "node/process-exit-as-throw": "error",
    "node/shebang": "error",
  },
};
